/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-2",
    "aws_cognito_identity_pool_id": "ap-northeast-2:a546963d-fe03-4345-999b-c641e6dd7d91",
    "aws_cognito_region": "ap-northeast-2",
    "aws_user_pools_id": "ap-northeast-2_BSoqsowcs",
    "aws_user_pools_web_client_id": "647m5cael3gmvqqj6g2nhkeu3k",
    "oauth": {}
};


export default awsmobile;
